CREATE USER tamarilt_ro1 WITH PASSWORD 'shopAPI_ro';
GRANT CONNECT ON DATABASE "shopAPI" TO tamarilt_ro1;
GRANT USAGE ON SCHEMA public TO tamarilt_ro1;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO tamarilt_ro1;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO tamarilt_ro1;

CREATE USER tamarilt_ro2 WITH PASSWORD 'shopAPI_ro';
GRANT CONNECT ON DATABASE "shopAPI" TO tamarilt_ro2;
GRANT USAGE ON SCHEMA public TO tamarilt_ro2;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO tamarilt_ro2;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO tamarilt_ro2;